#include "Gpio.h"



void RGBLed_Init(void){
	
	SIM->SCGC5 |= SIM_SCGC5_PORTB_MASK; 
	SIM->SCGC5 |= SIM_SCGC5_PORTD_MASK;
	
	PORTB->PCR[RED_LED_PIN] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[GREEN_LED_PIN] &= ~PORT_PCR_MUX_MASK;
	PORTD->PCR[BLUE_LED_PIN] &= ~PORT_PCR_MUX_MASK;
	
	PORTB->PCR[RED_LED_PIN] |= PORT_PCR_MUX(1);
	PORTB->PCR[GREEN_LED_PIN] |= PORT_PCR_MUX(1); 
	PORTD->PCR[BLUE_LED_PIN] |= PORT_PCR_MUX(1); 
	
	GPIOB->PDDR |= (1 << RED_LED_PIN);
	GPIOB->PDDR |= (1 << GREEN_LED_PIN);
	GPIOD->PDDR |= (1 << BLUE_LED_PIN);
	
	GPIOB->PCOR |= (1 << RED_LED_PIN);
	GPIOD->PCOR |= (1 << BLUE_LED_PIN);
	GPIOB->PCOR |= (1 << GREEN_LED_PIN);

}